kind: Deployment
apiVersion: apps/v1
metadata:
  name: machine-controller-manager
  labels:
    {{- include "mcm-deploy.labels" . | nindent 4 }}  
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: machine-controller-manager
  template:
    metadata:
      labels:
        app: machine-controller-manager
    spec:
      containers:
        - name: machine-controller-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ./machine-controller-manager
            - '--control-kubeconfig=inClusterConfig'
            - '--namespace={{ .Release.Namespace }}'
            - '--safety-up=2'
            - '--safety-down=1'
            - '--machine-drain-timeout=5m'
            - '--machine-health-timeout=10m'
            - '--machine-safety-orphan-vms-period=30m'
            - '--machine-safety-overshooting-period=1m'
            - --node-conditions=ReadonlyFilesystem,KernelDeadlock,DiskPressure,NetworkUnavailable
            - '--v=2'
          resources: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10258
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
      restartPolicy: Always
      serviceAccountName: machine-controller-manager
      serviceAccount: machine-controller-manager
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule