{{- if .Values.machinedeployment.enable }}
---
kind: MachineDeployment
apiVersion: machine.sapcloud.io/v1alpha1
metadata:
  name: worker-{{ .Values.machinedeployment.name }}
spec:
  minReadySeconds: 600
  replicas: {{ .Values.machinedeployment.replicas }}
  selector:
    matchLabels:
      deployment: {{ .Values.machinedeployment.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: {{ .Values.machinedeployment.name }}
    spec:
      class:
        kind: OpenStackMachineClass
        name: osclass-{{ .Values.machinedeployment.name }}
{{- end }}