kind: Secret
apiVersion: v1
metadata:
  name: ossec-{{ .Release.Name }}
stringData:
  authURL: {{ .Values.openstack.authURL }}
  domainName: {{ .Values.openstack.domainName }}
  username: {{ .Values.openstack.username }}
  password: {{ .Values.openstack.password }}
  tenantName: {{ .Values.openstack.tenantName }}
  userData: | {{ .Values.openstack.userData | nindent 4 }}
type: Opaque
