apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: machine-controller-manager-target
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: machine-controller-manager-target
subjects:
- kind: ServiceAccount
  name: machine-controller-manager
  namespace: machine-controller-manager